export const COLOR_PRIMARY = "#111827";           // Gray 900
export const COLOR_ACCENT = "#3B82F6";            // Blue 500
export const COLOR_ACCENT_HOVER = "#2563EB";      // Blue 600
export const COLOR_ACCENT_SHADOW = "#3B82F64D";   // Blue 500 @ 30% — button shadow
export const COLOR_DANGER = "#EF4444";            // Red 500
export const COLOR_DANGER_HOVER = "#B91C1C";      // Red 700
export const COLOR_SUCCESS = "#22C55E";           // Green 500
export const COLOR_BG = "#FFFFFF";
export const COLOR_WHITE = "#FFFFFF";             // Alias for explicit white usage
export const COLOR_TRANSPARENT = "#FFFFFF00";     // Fully transparent
export const COLOR_BORDER = "#E2E8F0";            // Slate 200
export const COLOR_MUTED = "#64748B";             // Slate 500
export const COLOR_HOVER_BG = "#F8FAFC";          // Slate 50
export const COLOR_SURFACE = "#F1F5F9";           // Slate 100 — button bg, indent toggle
export const COLOR_SHADOW = "#0F172A1A";          // Slate 900 @ 10% — drop shadow
export const COLOR_EDIT_ACTIVE_BG = "#EFF6FF";    // Blue 50 — active edit toggle + link chip
export const COLOR_REMOVE_ACTIVE_BG = "#FEF2F2";  // Red 50  — active remove toggle
export const COLOR_REMOVE_BTN_BG = "#FEE2E2";     // Red 100 — delete X button
export const COLOR_REMOVE_BTN_HOVER = "#FECACA";  // Red 200 — delete X button hover
export const COLOR_CHECKBOX_UNCHECKED = "#CBD5E1";// Slate 300 — unchecked checkbox stroke
export const COLOR_CHECKBOX_HOVER = "#94A3B8";    // Slate 400 — hovered checkbox stroke
export const COLOR_TASK_CHECKED = "#9CA3AF";      // Gray 400  — checked task text
export const COLOR_TASK_CHILD = "#4B5563";        // Gray 600  — child task text
export const COLOR_LINK_BORDER = "#BFDBFE";       // Blue 200  — link chip border
export const COLOR_LINK_HOVER = "#DBEAFE";        // Blue 100  — link chip hover

// ─── Dark theme ───────────────────────────────────────────────────────────────
export const DARK_COLOR_BG = "#1E293B";                 // Slate 800
export const DARK_COLOR_HOVER_BG = "#0F172A";           // Slate 900 — action bar + row hover
export const DARK_COLOR_PRIMARY = "#F1F5F9";            // Slate 100
export const DARK_COLOR_MUTED = "#94A3B8";              // Slate 400
export const DARK_COLOR_BORDER = "#334155";             // Slate 700
export const DARK_COLOR_SURFACE = "#475569";            // Slate 600
export const DARK_COLOR_TASK_CHILD = "#CBD5E1";         // Slate 300
export const DARK_COLOR_TASK_CHECKED = "#475569";       // Slate 600
export const DARK_COLOR_CHECKBOX_UNCHECKED = "#475569"; // Slate 600
export const DARK_COLOR_CHECKBOX_HOVER = "#64748B";     // Slate 500
export const DARK_COLOR_EDIT_ACTIVE_BG = "#1E3A5F";     // Deep blue — link chip + edit bg
export const DARK_COLOR_REMOVE_ACTIVE_BG = "#450A0A";   // Dark red  — remove toggle
export const DARK_COLOR_REMOVE_BTN_BG = "#7F1D1D";      // Red 900
export const DARK_COLOR_REMOVE_BTN_HOVER = "#991B1B";   // Red 800
export const DARK_COLOR_LINK_BORDER = "#1D4ED8";        // Blue 700
export const DARK_COLOR_LINK_HOVER = "#1E3A5F";         // Deep blue
export const DARK_COLOR_FLOAT_BTN = "#334155";          // Slate 700 — merge/float button bg
export const DARK_COLOR_SHADOW = "#00000066";           // Black 40%
